export const defaultSettingPresetId = 'sample-frame-match';

export const thematicSettingPresets = [
  {
    id: 'sample-frame-match',
    label: 'Sample frame match',
    modelId: 'realvisxl-v5',
    description: 'Closest to the supplied panoramic source images. Keeps source frames dominant with minimal redraw, no depth warp, no camera drift, and restrained contrast.',
    generation: {
      sampler: 'DPM++ 2M Karras',
      scheduler: 'Karras',
      steps: 28,
      cfgScale: 4.5,
      seedMode: 'fixed',
    },
    imageMorph: {
      sourceImageStrength: 0.55,
      denoiseStrength: 0.12,
      imageInfluenceDecay: 0.35,
      transitionDuration: 116,
      transitionEasing: 'ease-in-out',
      holdFramesBeforeMorph: 0,
      structuralLockStrength: 0.96,
      fogMaskAssistance: true,
    },
    motion: {
      zoom: 1,
      panX: 0,
      panY: 0,
      rotation: 0,
      depthWarpStrength: 0,
      cameraPathPreset: 'locked-source-morph',
      cadence: 1,
    },
    look: {
      contrast: 1.06,
      fogEmphasis: 0.56,
      bloom: 0.16,
      grain: 0.03,
      vignette: 0.1,
      monochromeToColourBias: 0.42,
    },
    output: {
      renderQuality: 'review-preview',
    },
  },
  {
    id: 'misty-maritime-night',
    label: 'Misty maritime night',
    modelId: 'realvisxl-v5',
    description: 'Preserves the long-distance night waterfront while allowing more mist, glow, and atmospheric watercolor softness.',
    generation: {
      sampler: 'DPM++ 2M Karras',
      scheduler: 'Karras',
      steps: 30,
      cfgScale: 6.5,
      seedMode: 'fixed',
    },
    imageMorph: {
      sourceImageStrength: 0.58,
      denoiseStrength: 0.18,
      imageInfluenceDecay: 0.34,
      transitionDuration: 108,
      transitionEasing: 'ease-in-out',
      holdFramesBeforeMorph: 0,
      structuralLockStrength: 0.92,
      fogMaskAssistance: true,
    },
    motion: {
      zoom: 1.004,
      panX: 0,
      panY: 0,
      rotation: 0,
      depthWarpStrength: 0,
      cameraPathPreset: 'locked-source-morph',
      cadence: 1,
    },
    look: {
      contrast: 1,
      fogEmphasis: 0.82,
      bloom: 0.24,
      grain: 0.04,
      vignette: 0.12,
      monochromeToColourBias: 0.48,
    },
    output: {
      renderQuality: 'review-preview',
    },
  },
  {
    id: 'cinematic-midjourney-concept',
    label: 'Cinematic concept polish',
    modelId: 'juggernaut-xl-v9',
    description: 'Closest configured preset for a Midjourney-like cinematic concept-art finish, while still keeping source images as anchors.',
    generation: {
      sampler: 'DPM++ 2M Karras',
      scheduler: 'Karras',
      steps: 34,
      cfgScale: 7.5,
      seedMode: 'fixed',
    },
    imageMorph: {
      sourceImageStrength: 0.62,
      denoiseStrength: 0.26,
      imageInfluenceDecay: 0.32,
      transitionDuration: 96,
      transitionEasing: 'ease-in-out',
      holdFramesBeforeMorph: 0,
      structuralLockStrength: 0.86,
      fogMaskAssistance: true,
    },
    motion: {
      zoom: 1.008,
      panX: 0,
      panY: 0,
      rotation: 0,
      depthWarpStrength: 0,
      cameraPathPreset: 'slow-push',
      cadence: 1,
    },
    look: {
      contrast: 1.18,
      fogEmphasis: 0.68,
      bloom: 0.32,
      grain: 0.04,
      vignette: 0.16,
      monochromeToColourBias: 0.55,
    },
    output: {
      renderQuality: 'review-preview',
    },
  },
  {
    id: 'soft-watercolor-memory',
    label: 'Soft watercolor memory',
    modelId: 'realvisxl-v5',
    description: 'Softens the skyline into mist and painterly glow without pushing into graphic line art or mosaic abstraction.',
    generation: {
      sampler: 'DPM++ 2M Karras',
      scheduler: 'Karras',
      steps: 30,
      cfgScale: 6,
      seedMode: 'fixed',
    },
    imageMorph: {
      sourceImageStrength: 0.6,
      denoiseStrength: 0.2,
      imageInfluenceDecay: 0.34,
      transitionDuration: 108,
      transitionEasing: 'ease-in-out',
      holdFramesBeforeMorph: 0,
      structuralLockStrength: 0.9,
      fogMaskAssistance: true,
    },
    motion: {
      zoom: 1.002,
      panX: 0,
      panY: 0,
      rotation: 0,
      depthWarpStrength: 0,
      cameraPathPreset: 'locked-source-morph',
      cadence: 1,
    },
    look: {
      contrast: 0.92,
      fogEmphasis: 0.9,
      bloom: 0.22,
      grain: 0.02,
      vignette: 0.08,
      monochromeToColourBias: 0.46,
    },
    output: {
      renderQuality: 'review-preview',
    },
  },
  {
    id: 'fast-alignment-test',
    label: 'Fast alignment test',
    modelId: 'sd15-baseline',
    description: 'Lower-cost backend check for source alignment and folder/output behavior before running slower creative passes.',
    generation: {
      sampler: 'DPM++ 2M Karras',
      scheduler: 'Karras',
      steps: 18,
      cfgScale: 5,
      seedMode: 'fixed',
    },
    imageMorph: {
      sourceImageStrength: 0.5,
      denoiseStrength: 0.1,
      imageInfluenceDecay: 0.3,
      transitionDuration: 96,
      transitionEasing: 'ease-in-out',
      holdFramesBeforeMorph: 0,
      structuralLockStrength: 0.94,
      fogMaskAssistance: true,
    },
    motion: {
      zoom: 1,
      panX: 0,
      panY: 0,
      rotation: 0,
      depthWarpStrength: 0,
      cameraPathPreset: 'locked-source-morph',
      cadence: 1,
    },
    look: {
      contrast: 1,
      fogEmphasis: 0.58,
      bloom: 0.12,
      grain: 0.03,
      vignette: 0.08,
      monochromeToColourBias: 0.42,
    },
    output: {
      renderQuality: 'fast-preview',
    },
  },
];

export function getThematicSettingPreset(presetId) {
  return thematicSettingPresets.find((preset) => preset.id === presetId) ?? thematicSettingPresets[0];
}
